src/Entity/SakonninTemplate.php
<?php

namespace BisonLab\SakonninBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * SakonninTemplate
 */
#[ORM\Table(name: 'sakonnin_template')]
#[ORM\UniqueConstraint(name: 'sakonnin_template_tuple_idx', columns: ['name', 'lang_code'])]
#[ORM\Entity(repositoryClass: 'BisonLab\SakonninBundle\Repository\SakonninTemplateRepository')]
class SakonninTemplate
{
    /**
     * @var int
     */
    #[ORM\Column(name: 'id', type: 'integer')]
    #[ORM\Id]
    #[ORM\GeneratedValue]
    private $id;

    /**
     * @var string
     */
    #[ORM\Column(name: 'name', type: 'string', length: 50)]
    private $name;

    /**
     * @var string
     */
    #[ORM\Column(name: 'description', type: 'text', nullable: true)]
    private $description;

    /**
     * @var string
     */
    #[ORM\Column(name: 'lang_code', type: 'string', length: 7)]
    private $lang_code;

    /**
     * @var string
     */
    #[ORM\Column(name: 'template', type: 'text')]
    private $template;

    #[ORM\OneToMany(targetEntity: 'MessageType', mappedBy: 'sakonnin_template', fetch: 'EXTRA_LAZY')]
    private $message_types;

    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     *
     * @return SakonninTemplate
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set description
     *
     * @param string $description
     *
     * @return this
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Set lang_code
     *
     * @param string $lang_code
     *
     * @return SakonninLangCode
     */
    public function setLangCode($lang_code)
    {
        $this->lang_code = $lang_code;

        return $this;
    }

    /**
     * Get lang_code
     *
     * @return string
     */
    public function getLangCode()
    {
        return $this->lang_code;
    }

    /**
     * Set template
     *
     * @param string $template
     *
     * @return SakonninTemplate
     */
    public function setTemplate($template)
    {
        $this->template = $template;

        return $this;
    }

    /**
     * Get template
     *
     * @return string
     */
    public function getTemplate()
    {
        return $this->template;
    }

    /**
     * Add message_types
     *
     * @param \BisonLab\SakonninBundle\Entity\MessageType $message_types
     * @return MessageTypeType
     */
    public function addMessageType(\BisonLab\SakonninBundle\Entity\MessageType $message_types)
    {
        $this->message_types[] = $message_types;

        return $this;
    }

    /**
     * Remove message_types
     *
     * @param \BisonLab\SakonninBundle\Entity\MessageType $message_types
     */
    public function removeMessageType(\BisonLab\SakonninBundle\Entity\MessageType $message_types)
    {
        $this->message_types->removeElement($message_types);
    }

    /**
     * Get message_types
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getMessageTypes()
    {
        return $this->message_types;
    }

    public function isDeleteable()
    {
        return $this->getMessageTypes()->count() == 0;
    }

    public function __toString()
    {
        return $this->getName();
    }
}

src/Form/SakonninTemplateType.php
<?php

namespace BisonLab\SakonninBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

use Symfony\Component\Form\Extension\Core\Type\TextType;
use Norzechowicz\AceEditorBundle\Form\Extension\AceEditor\Type\AceEditorType;

class SakonninTemplateType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', TextType::class, array('label' => "Name", 'required' => true, "attr" => array("size" => "50")))
            ->add('description')
            ->add('lang_code', TextType::class, array(
                'label' => "Language code:",
                'required' => true,
                "attr" => array("size" => "7")))
            ->add('template', AceEditorType::class, array(
                'label' => 'Template',
                'required' => false,
                'wrapper_attr' => array(), // aceeditor wrapper html attributes.
                // 'width' => 700,
                'width' => '100%',
                'height' => '400px',
                'font_size' => 12,
                'mode' => 'ace/mode/twig', // every single default mode must have ace/mode/* prefix
                'theme' => 'ace/theme/tomorrow', // every single default theme must have ace/theme/* prefix
                'tab_size' => null,
                'read_only' => null,
                'use_soft_tabs' => null,
                'use_wrap_mode' => true,
                'show_print_margin' => null,
                'show_invisibles' => null,
                'highlight_active_line' => null,
                'options_enable_basic_autocompletion' => true,
                'options_enable_live_autocompletion' => true,
                'options_enable_snippets' => false,
                'keyboard_handler' => null
              ));
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults(array(
            'data_class' => 'BisonLab\SakonninBundle\Entity\SakonninTemplate'
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix(): string
    {
        return 'sakonnintemplate';
    }
}

src/Controller/SakonninTemplateController.php
<?php

namespace BisonLab\SakonninBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Contracts\Translation\TranslatorInterface;
use Doctrine\Persistence\ManagerRegistry;

use BisonLab\SakonninBundle\Entity\SakonninTemplate;
use BisonLab\SakonninBundle\Form\SakonninTemplateType;

/**
 * Sakonnintemplate controller.
 */
#[Route(path: 'sakonnin_template')]
class SakonninTemplateController extends AbstractController
{
    use \BisonLab\CommonBundle\Controller\CommonControllerTrait;
    use \BisonLab\SakonninBundle\Lib\CommonStuff;

    public function __construct(
        private ManagerRegistry $managerRegistry
    ) {
    }

    /**
     * Lists all sakonninTemplate entities.
     */
    #[Route(path: '/', name: 'sakonnintemplate_index', methods: ['GET'])]
    public function indexAction()
    {
        $em = $this->getDoctrineManager();
        $sakonninTemplates = $em->getRepository(SakonninTemplate::class)->findAll();
        return $this->render('@BisonLabSakonnin/SakonninTemplate/index.html.twig',
            array( 'sakonninTemplates' => $sakonninTemplates,));
    }

    /**
     * Creates a new sakonninTemplate entity.
     */
    #[Route(path: '/new', name: 'sakonnintemplate_new', methods: ['GET', 'POST'])]
    public function newAction(Request $request, TranslatorInterface $translator)
    {
        $sakonninTemplate = new Sakonnintemplate();
        $default_lang_code = $translator->getLocale();
        $sakonninTemplate->setLangCode($default_lang_code);
        $form = $this->createForm(SakonninTemplateType::class, $sakonninTemplate);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrineManager();
            $entityManager->persist($sakonninTemplate);
            $entityManager->flush();

            return $this->redirectToRoute('sakonnintemplate_show', array('id' => $sakonninTemplate->getId()));
        }

        return $this->render('@BisonLabSakonnin/SakonninTemplate/new.html.twig',
            array(
            'sakonninTemplate' => $sakonninTemplate,
            'form' => $form->createView(),
        ));
    }

    /**
     * Finds and displays a sakonninTemplate entity.
     */
    #[Route(path: '/{id:sakonninTemplate}', name: 'sakonnintemplate_show', methods: ['GET'], requirements: ['id' => '\d+'])]
    public function showAction(SakonninTemplate $sakonninTemplate)
    {
        return $this->render('@BisonLabSakonnin/SakonninTemplate/show.html.twig',
            array(
            'sakonninTemplate' => $sakonninTemplate,
        ));
    }

    /**
     * Displays a form to edit an existing sakonninTemplate entity.
     */
    #[Route(path: '/{id:sakonninTemplate}/edit', name: 'sakonnintemplate_edit', methods: ['GET', 'POST'])]
    public function editAction(Request $request, SakonninTemplate $sakonninTemplate)
    {
        $editForm = $this->createForm(SakonninTemplateType::class, $sakonninTemplate);
        $editForm->handleRequest($request);

        if ($editForm->isSubmitted() && $editForm->isValid()) {
            $this->getDoctrineManager()->flush();

            return $this->redirectToRoute('sakonnintemplate_show', array('id' => $sakonninTemplate->getId()));
        }

        return $this->render('@BisonLabSakonnin/SakonninTemplate/edit.html.twig',
            array(
                'sakonninTemplate' => $sakonninTemplate,
                'edit_form' => $editForm->createView(),
        ));
    }

    /**
     * Deletes a sakonninTemplate entity.
     */
    #[Route(path: '/{id:sakonninTemplate}/delete', name: 'sakonnintemplate_delete', methods: ['POST', 'DELETE'])]
    public function deleteAction(Request $request, SakonninTemplate $sakonninTemplate)
    {
        if ($this->isCsrfTokenValid('delete'.$sakonninTemplate->getId(), $request->request->get('_token')) && $sakonninTemplate->isDeleteable()) {
            $entityManager = $this->getDoctrineManager();
            $entityManager->remove($sakonninTemplate);
            $entityManager->flush();
            return $this->redirectToRoute('sakonnintemplate_index');
        }
        return $this->redirectToRoute('sakonnintemplate_show', array('id' => $sakonninTemplate->getId()));
    }
}

templates/SakonninTemplate/_delete_form.html.twig
<form id="stDeleteForm" method="post" action="{{ path('sakonnintemplate_delete', {'id': sakonninTemplate.id}) }}" onsubmit="return confirm('Are you sure you want to delete this Template?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ sakonninTemplate.id) }}">
    <input type="submit" value="Delete Template">
</form>

templates/SakonninTemplate/edit.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1>Sakonnintemplate edit</h1>

    {{ form_start(edit_form) }}
        {{ form_widget(edit_form) }}
        <input type="submit" value="Save" />
    {{ form_end(edit_form) }}
    <a  href="{{ path('sakonnintemplate_show', { 'id': sakonninTemplate.id }) }}">
    <button>Cancel</button>
    </a>
    {% if sakonninTemplate.deleteable %}
    {{ include('@BisonLabSakonnin/SakonninTemplate/_delete_form.html.twig') }}
    {% endif %}
{% endblock %}

templates/SakonninTemplate/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1>Templates</h1>

    <table class="table table-striped table-bordered table-sm">
        <thead>
            <tr>
                <th>Name</th>
                <th>Description</th>
                <th>Langcode</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for sakonninTemplate in sakonninTemplates %}
            <tr>
                <td><a href="{{ path('sakonnintemplate_show', { 'id': sakonninTemplate.id }) }}">{{ sakonninTemplate.name }}</a></td>
                <td>{{ sakonninTemplate.description }}</td>
                <td>{{ sakonninTemplate.langCode }}</td>
                <td>
                    <ul>
                        <li>
                            <a href="{{ path('sakonnintemplate_show', { 'id': sakonninTemplate.id }) }}">show</a>
                        </li>
                        <li>
                            <a href="{{ path('sakonnintemplate_edit', { 'id': sakonninTemplate.id }) }}">edit</a>
                        </li>
                    </ul>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <ul>
        <li>
            <a href="{{ path('sakonnintemplate_new') }}">Create a new Template</a>
        </li>
    </ul>
{% endblock %}

templates/SakonninTemplate/new.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1>Create a new Template</h1>

    {{ form_start(form) }}
        {{ form_widget(form) }}
        <input type="submit" value="Create" />
    {{ form_end(form) }}
     <button class="btn"><a href="{{ path('sakonnintemplate_index') }}">Cancel</a></button>
{% endblock %}

templates/SakonninTemplate/show.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1>Sakonnintemplate</h1>

    <table class="sakonnin_properties">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ sakonninTemplate.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ sakonninTemplate.name }}</td>
            </tr>
            <tr>
                <th>Langcode</th>
                <td>{{ sakonninTemplate.langCode }}</td>
            </tr>
            <tr>
                <th>Template</th>
                <td>{{ sakonninTemplate.template }}</td>
            </tr>
        </tbody>
    </table>

    <ul>
        <li>
            <a href="{{ path('sakonnintemplate_index') }}">
            <button>Template List</button>
            </a>
        </li>
        <li>
            <a href="{{ path('sakonnintemplate_edit', { 'id': sakonninTemplate.id }) }}">
            <button>Edit</button>
            </a>
        </li>
        {% if sakonninTemplate.deleteable %}
        <li>
        {{ include('@BisonLabSakonnin/SakonninTemplate/_delete_form.html.twig') }}
        </li>
        {% endif %}
    </ul>
{% endblock %}